var weapons = [
    {name:"Club",damage:4},
    {name:"Dagger",damage:4},
    {name:"Greatclub",damage:8},
    {name:"Handaxe",damage:6},
    {name:"Javelin",damage:6},
    {name:"Light Hammer",damage:4},
    {name:"Mace",damage:6},
    {name:"Quarterstaff",damage:6},
    {name:"Sickle",damage:4},
    {name:"Spear",damage:6},
    {name:"Crossbow",damage:8},
    {name:"Dart",damage:4},
    {name:"Shortbow",damage:6},
    {name:"Sling",damage:4},
    {name:"Battleaxe",damage:8},
    {name:"Flail",damage:8},
    {name:"Greatsword",damage:12},
    {name:"Halberd",damage:10},
    {name:"Lance",damage:12},
    {name:"Longsword",damage:8},
    {name:"Morningstar",damage:8},
    {name:"Scimitar",damage:6},
    {name:"Shortsword",damage:6},
    {name:"Trident",damage:6},
    {name:"Warhammer",damage:8},
    {name:"Whip",damage:4},
    {name:"Longbow",damage:8}
];

var armors = [
    {type:"Padded Armor",arm:11},
    {type:"Leather Armor",arm:11},
    {type:"Studded Leather Armor",arm:12},
    {type:"Hide",arm:12},
    {type:"Chain Shirt",arm:13},
    {type:"Scale Mail",arm:14},
    {type:"Breastplate",arm:14},
    {type:"Ring Mail",arm:14},
    {type:"Chain Mail",arm:16}
]

var spells = [
    {name:"Acid Splash",level:0,sorcerer:true,wizard:true},
    {name:"Blade Ward",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Chill Touch",level:0,sorcerer:true,warlock:true,wizard:true},
    {name:"Control Flames",level:0,druid:true,sorcerer:true,wizard:true},
    {name:"Create Bonfire",level:0,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Dancing Lights",level:0,bard:true,sorcerer:true,wizard:true},
    {name:"Druidcraft",level:0,druid:true},
    {name:"Eldritch Blast",level:0,warlock:true},
    {name:"Fire Bolt",level:0,sorcerer:true,wizard:true},
    {name:"Friends",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Frostbite",level:0,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Guidance",level:0,cleric:true,druid:true},
    {name:"Gust",level:0,druid:true,sorcerer:true,wizard:true},
    {name:"Light",level:0,bard:true,cleric:true,sorcerer:true,wizard:true},
    {name:"Mage Hand",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Magic Stone",level:0,druid:true,warlock:true},
    {name:"Mending",level:0,bard:true,cleric:true,druid:true,sorcerer:true,wizard:true},
    {name:"Message",level:0,bard:true,sorcerer:true,wizard:true},
    {name:"Minor Illusion",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Mold Earth",level:0,druid:true,sorcerer:true,wizard:true},
    {name:"Poison Spray",level:0,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Prestidigitation",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Produce Flame",level:0,druid:true},
    {name:"Ray of Frost",level:0,sorcerer:true,wizard:true},
    {name:"Resistance",level:0,cleric:true,druid:true},
    {name:"Sacred Flame",level:0,cleric:true},
    {name:"Shape Water",level:0,druid:true,sorcerer:true,wizard:true},
    {name:"Shillelagh",level:0,druid:true},
    {name:"Shocking Grasp",level:0,sorcerer:true,wizard:true},
    {name:"Spare the Dying",level:0,cleric:true},
    {name:"Thaumaturgy",level:0,cleric:true},
    {name:"Thorn Whip",level:0,druid:true},
    {name:"Thunderclap",level:0,bard:true,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"True Strike",level:0,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Vicious Mockery",level:0,bard:true},
    {name:"Absorb Elements",level:1,druid:true,ranger:true,wizard:true},
    {name:"Alarm",level:1,ranger:true,wizard:true},
    {name:"Animal Friendship",level:1,bard:true,druid:true,ranger:true},
    {name:"Armor of Agathys",level:1,warlock:true},
    {name:"Arms of Hadar",level:1,warlock:true},
    {name:"Bane",level:1,bard:true,cleric:true},
    {name:"Beast Bond",level:1,druid:true,ranger:true},
    {name:"Bless",level:1,cleric:true,paladin:true},
    {name:"Burning Hands",level:1,sorcerer:true,wizard:true},
    {name:"Catapult",level:1,sorcerer:true,wizard:true},
    {name:"Charm Person",level:1,bard:true,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Chromatic Orb",level:1,sorcerer:true,wizard:true},
    {name:"Color Spray",level:1,sorcerer:true,wizard:true},
    {name:"Command",level:1,cleric:true,paladin:true},
    {name:"Compelled Duel",level:1,paladin:true},
    {name:"Comprehend Languages",level:1,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Create or Destroy Water",level:1,cleric:true,druid:true},
    {name:"Cure Wounds",level:1,bard:true,cleric:true,druid:true,paladin:true,ranger:true},
    {name:"Detect Evil and Good",level:1,cleric:true,paladin:true},
    {name:"Detect Magic",level:1,bard:true,cleric:true,druid:true,paladin:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Detect Poison and Disease",level:1,cleric:true,druid:true,paladin:true,ranger:true},
    {name:"Disguise Self",level:1,bard:true,sorcerer:true,wizard:true},
    {name:"Dissonant Whispers",level:1,bard:true},
    {name:"Divine Favor",level:1,paladin:true},
    {name:"Earth Tremor",level:1,bard:true,druid:true,sorcerer:true,wizard:true},
    {name:"Ensnaring Strike",level:1,ranger:true},
    {name:"Entangle",level:1,druid:true},
    {name:"Expeditious Retreat",level:1,sorcerer:true,warlock:true,wizard:true},
    {name:"Faerie Fire",level:1,bard:true,druid:true},
    {name:"False Life",level:1,sorcerer:true,wizard:true},
    {name:"Feather Fall",level:1,bard:true,sorcerer:true,wizard:true},
    {name:"Find Familiar",level:1,wizard:true},
    {name:"Fog Cloud",level:1,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Goodberry",level:1,druid:true,ranger:true},
    {name:"Grease",level:1,wizard:true},
    {name:"Guiding Bolt",level:1,cleric:true},
    {name:"Hail of Thorns",level:1,ranger:true},
    {name:"Healing Word",level:1,bard:true,cleric:true,druid:true},
    {name:"Hellish Rebuke",level:1,warlock:true},
    {name:"Heroism",level:1,bard:true,paladin:true},
    {name:"Hex",level:1,warlock:true},
    {name:"Hunter's Mark",level:1,ranger:true},
    {name:"Ice Knife",level:1,druid:true,sorcerer:true,wizard:true},
    {name:"Identify",level:1,bard:true,wizard:true},
    {name:"Illusory Script",level:1,bard:true,warlock:true,wizard:true},
    {name:"Inflict Wounds",level:1,cleric:true},
    {name:"Jump",level:1,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Longstrider",level:1,bard:true,druid:true,ranger:true,wizard:true},
    {name:"Mage Armor",level:1,sorcerer:true,wizard:true},
    {name:"Magic Missile",level:1,sorcerer:true,wizard:true},
    {name:"Protection from Evil and Good",level:1,cleric:true,paladin:true,warlock:true,wizard:true},
    {name:"Purify Food and Drink",level:1,cleric:true,druid:true,paladin:true},
    {name:"Ray of Sickness",level:1,sorcerer:true,wizard:true},
    {name:"Sanctuary",level:1,cleric:true},
    {name:"Searing Smite",level:1,paladin:true},
    {name:"Shield",level:1,sorcerer:true,wizard:true},
    {name:"Shield of Faith",level:1,cleric:true,paladin:true},
    {name:"Silent Image",level:1,bard:true,sorcerer:true,wizard:true},
    {name:"Sleep",level:1,bard:true,sorcerer:true,wizard:true},
    {name:"Speak with Animals",level:1,bard:true,druid:true,ranger:true},
    {name:"Tasha's Hideous Laughter",level:1,bard:true,wizard:true},
    {name:"Tenser's Floating Disk",level:1,wizard:true},
    {name:"Thunderous Smite",level:1,paladin:true},
    {name:"Thunderwave",level:1,bard:true,druid:true,sorcerer:true,wizard:true},
    {name:"Unseen Servant",level:1,bard:true,warlock:true,wizard:true},
    {name:"Witch Bolt",level:1,sorcerer:true,warlock:true,wizard:true},
    {name:"Wrathful Smite",level:1,paladin:true},
    {name:"Aganazzar's Scorcher",level:2,sorcerer:true,wizard:true},
    {name:"Aid",level:2,cleric:true,paladin:true},
    {name:"Alter Self",level:2,sorcerer:true,wizard:true},
    {name:"Animal Messenger",level:2,bard:true,druid:true,ranger:true},
    {name:"Arcane Lock",level:2,wizard:true},
    {name:"Augury",level:2,cleric:true},
    {name:"Barkskin",level:2,druid:true,ranger:true},
    {name:"Beast Sense",level:2,druid:true,ranger:true},
    {name:"Blindness/Deafness",level:2,bard:true,cleric:true,sorcerer:true,wizard:true},
    {name:"Blur",level:2,sorcerer:true,wizard:true},
    {name:"Branding Smite",level:2,paladin:true},
    {name:"Calm Emotions",level:2,bard:true,cleric:true},
    {name:"Cloud of Daggers",level:2,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Continual Flame",level:2,cleric:true,wizard:true},
    {name:"Cordon of Arrows",level:2,ranger:true},
    {name:"Crown of Madness",level:2,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Darkness",level:2,sorcerer:true,warlock:true,wizard:true},
    {name:"Darkvision",level:2,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Detect Thoughts",level:2,bard:true,sorcerer:true,wizard:true},
    {name:"Dust Devil",level:2,druid:true,sorcerer:true,wizard:true},
    {name:"Earthbind",level:2,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Enhance Ability",level:2,bard:true,cleric:true,druid:true,sorcerer:true},
    {name:"Enlarge/Reduce",level:2,sorcerer:true,wizard:true},
    {name:"Enthrall",level:2,bard:true,warlock:true},
    {name:"Find Steed",level:2,paladin:true},
    {name:"Find Traps",level:2,cleric:true,druid:true,ranger:true},
    {name:"Flame Blade",level:2,druid:true},
    {name:"Flaming Sphere",level:2,druid:true,wizard:true},
    {name:"Gentle Repose",level:2,cleric:true,wizard:true},
    {name:"Gust of Wind",level:2,druid:true,sorcerer:true,wizard:true},
    {name:"Heat Metal",level:2,bard:true,druid:true},
    {name:"Hold Person",level:2,bard:true,cleric:true,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Invisibility",level:2,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Knock",level:2,bard:true,sorcerer:true,wizard:true},
    {name:"Lesser Restoration",level:2,bard:true,cleric:true,druid:true,paladin:true,ranger:true},
    {name:"Levitate",level:2,sorcerer:true,wizard:true},
    {name:"Locate Animals or Plants",level:2,bard:true,druid:true,ranger:true},
    {name:"Locate Object",level:2,bard:true,cleric:true,druid:true,paladin:true,ranger:true,wizard:true},
    {name:"Magic Mouth",level:2,bard:true,wizard:true},
    {name:"Magic Weapon",level:2,paladin:true,wizard:true},
    {name:"Maximillian's Earthen Grasp",level:2,sorcerer:true,wizard:true},
    {name:"Melf's Acid Arrow",level:2,wizard:true},
    {name:"Mirror Image",level:2,sorcerer:true,warlock:true,wizard:true},
    {name:"Misty Step",level:2,sorcerer:true,warlock:true,wizard:true},
    {name:"Moonbeam",level:2,druid:true},
    {name:"Nystul's Magic Aura",level:2,wizard:true},
    {name:"Pass without Trace",level:2,druid:true,ranger:true},
    {name:"Phantasmal Force",level:2,bard:true,sorcerer:true,wizard:true},
    {name:"Prayer of Healing",level:2,cleric:true},
    {name:"Protection from Poison",level:2,cleric:true,druid:true,paladin:true,ranger:true},
    {name:"Pyrotechnics",level:2,bard:true,sorcerer:true,wizard:true},
    {name:"Ray of Enfeeblement",level:2,warlock:true,wizard:true},
    {name:"Rope Trick",level:2,wizard:true},
    {name:"Scorching Ray",level:2,sorcerer:true,wizard:true},
    {name:"See Invisibility",level:2,bard:true,sorcerer:true,wizard:true},
    {name:"Shatter",level:2,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Silence",level:2,bard:true,cleric:true,ranger:true},
    {name:"Skywrite",level:2,bard:true,druid:true,wizard:true},
    {name:"Snilloc's Snowball Swarm",level:2,sorcerer:true,wizard:true},
    {name:"Spider Climb",level:2,sorcerer:true,warlock:true,wizard:true},
    {name:"Spike Growth",level:2,druid:true,ranger:true},
    {name:"Spiritual Weapon",level:2,cleric:true},
    {name:"Suggestion",level:2,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Warding Bond",level:2,cleric:true},
    {name:"Warding Wind",level:2,bard:true,druid:true,sorcerer:true},
    {name:"Web",level:2,sorcerer:true,wizard:true},
    {name:"Zone of Truth",level:2,bard:true,cleric:true,paladin:true},
    {name:"Animate Dead",level:3,cleric:true,wizard:true},
    {name:"Aura of Vitality",level:3,paladin:true},
    {name:"Beacon of Hope",level:3,cleric:true},
    {name:"Bestow Curse",level:3,bard:true,cleric:true,wizard:true},
    {name:"Blinding Smite",level:3,paladin:true},
    {name:"Blink",level:3,sorcerer:true,wizard:true},
    {name:"Call Lightning",level:3,druid:true},
    {name:"Clairvoyance",level:3,bard:true,cleric:true,sorcerer:true,wizard:true},
    {name:"Conjure Animals",level:3,druid:true,ranger:true},
    {name:"Conjure Barrage",level:3,ranger:true},
    {name:"Counterspell",level:3,sorcerer:true,warlock:true,wizard:true},
    {name:"Create Food and Water",level:3,cleric:true,paladin:true},
    {name:"Crusader's Mantle",level:3,paladin:true},
    {name:"Daylight",level:3,cleric:true,druid:true,paladin:true,ranger:true,sorcerer:true},
    {name:"Dispel Magic",level:3,bard:true,cleric:true,druid:true,paladin:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Elemental Weapon",level:3,paladin:true},
    {name:"Erupting Earth",level:3,druid:true,sorcerer:true,wizard:true},
    {name:"Fear",level:3,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Feign Death",level:3,bard:true,cleric:true,druid:true,wizard:true},
    {name:"Fireball",level:3,sorcerer:true,wizard:true},
    {name:"Flame Arrows",level:3,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Fly",level:3,sorcerer:true,warlock:true,wizard:true},
    {name:"Gaseous Form",level:3,sorcerer:true,warlock:true,wizard:true},
    {name:"Glyph of Warding",level:3,bard:true,cleric:true,wizard:true},
    {name:"Haste",level:3,sorcerer:true,wizard:true},
    {name:"Hunger of Hadar",level:3,warlock:true},
    {name:"Hypnotic Pattern",level:3,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Leomund's Tiny Hut",level:3,bard:true,wizard:true},
    {name:"Lightning Arrow",level:3,ranger:true},
    {name:"Lightning Bolt",level:3,sorcerer:true,wizard:true},
    {name:"Magic Circle",level:3,cleric:true,paladin:true,warlock:true,wizard:true},
    {name:"Major Image",level:3,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Mass Healing Word",level:3,cleric:true},
    {name:"Meld into Stone",level:3,cleric:true,druid:true},
    {name:"Melf's Minute Meteors",level:3,sorcerer:true,wizard:true},
    {name:"Nondetection",level:3,bard:true,ranger:true,wizard:true},
    {name:"Phantom Steed",level:3,wizard:true},
    {name:"Plant Growth",level:3,bard:true,druid:true,ranger:true},
    {name:"Protection from Energy",level:3,cleric:true,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Remove Curse",level:3,cleric:true,paladin:true,warlock:true,wizard:true},
    {name:"Revivify",level:3,cleric:true,paladin:true},
    {name:"Sending",level:3,bard:true,cleric:true,wizard:true},
    {name:"Sleet Storm",level:3,druid:true,sorcerer:true,wizard:true},
    {name:"Slow",level:3,sorcerer:true,wizard:true},
    {name:"Speak with Dead",level:3,bard:true,cleric:true},
    {name:"Speak with Plants",level:3,bard:true,druid:true,ranger:true},
    {name:"Spirit Guardians",level:3,cleric:true},
    {name:"Stinking Cloud",level:3,bard:true,sorcerer:true,wizard:true},
    {name:"Tidal Wave",level:3,druid:true,wizard:true},
    {name:"Tongues",level:3,bard:true,cleric:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Vampiric Touch",level:3,warlock:true,wizard:true},
    {name:"Wall of Sand",level:3,wizard:true},
    {name:"Wall of Water",level:3,druid:true,sorcerer:true,wizard:true},
    {name:"Water Breathing",level:3,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Water Walk",level:3,cleric:true,druid:true,ranger:true,sorcerer:true},
    {name:"Wind Wall",level:3,druid:true,ranger:true},
    {name:"Arcane Eye",level:4,wizard:true},
    {name:"Aura of Life",level:4,paladin:true},
    {name:"Aura of Purity",level:4},
    {name:"Banishment",level:4,cleric:true,paladin:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Blight",level:4,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Compulsion",level:4,bard:true},
    {name:"Confusion",level:4,bard:true,druid:true,sorcerer:true,wizard:true},
    {name:"Conjure Minor Elementals",level:4,druid:true,wizard:true},
    {name:"Conjure Woodland Beings",level:4,druid:true,ranger:true},
    {name:"Control Water",level:4,cleric:true,druid:true,wizard:true},
    {name:"Death Ward",level:4,cleric:true,paladin:true},
    {name:"Dimension Door",level:4,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Divination",level:4,cleric:true},
    {name:"Dominate Beast",level:4,druid:true,sorcerer:true},
    {name:"Elemental Bane",level:4,druid:true,warlock:true,wizard:true},
    {name:"Evard's Black Tentacles",level:4,wizard:true},
    {name:"Fabricate",level:4,wizard:true},
    {name:"Fire Shield",level:4,wizard:true},
    {name:"Freedom of Movement",level:4,bard:true,cleric:true,druid:true,ranger:true},
    {name:"Giant Insect",level:4,druid:true},
    {name:"Grasping Vine",level:4,druid:true,ranger:true},
    {name:"Greater Invisibility",level:4,bard:true,sorcerer:true,wizard:true},
    {name:"Guardian of Faith",level:4,cleric:true},
    {name:"Hallucinatory Terrain",level:4,bard:true,druid:true,warlock:true,wizard:true},
    {name:"Ice Storm",level:4,druid:true,sorcerer:true,wizard:true},
    {name:"Leomund's Secret Chest",level:4,wizard:true},
    {name:"Locate Creature",level:4,bard:true,cleric:true,druid:true,paladin:true,ranger:true,wizard:true},
    {name:"Mordenkainen's Faithful Hound",level:4,wizard:true},
    {name:"Mordenkainen's Private Sanctum",level:4,wizard:true},
    {name:"Otiluke's Resilient Sphere",level:4,wizard:true},
    {name:"Phantasmal Killer",level:4,wizard:true},
    {name:"Polymorph",level:4,bard:true,druid:true,sorcerer:true,wizard:true},
    {name:"Staggering Smite",level:4,paladin:true},
    {name:"Stone Shape",level:4,cleric:true,druid:true,wizard:true},
    {name:"Stoneskin",level:4,druid:true,ranger:true,sorcerer:true,wizard:true},
    {name:"Storm Sphere",level:4,sorcerer:true,wizard:true},
    {name:"Vitriolic Sphere",level:4,sorcerer:true,wizard:true},
    {name:"Wall of Fire",level:4,druid:true,sorcerer:true,wizard:true},
    {name:"Watery Sphere",level:4,druid:true,sorcerer:true,wizard:true},
    {name:"Animate Objects",level:5,bard:true,sorcerer:true,wizard:true},
    {name:"Antilife Shell",level:5,druid:true},
    {name:"Awaken",level:5,bard:true,druid:true},
    {name:"Banishing Smite",level:5,paladin:true},
    {name:"Bigby's Hand",level:5,wizard:true},
    {name:"Circle of Power",level:5,paladin:true},
    {name:"Cloudkill",level:5,sorcerer:true,wizard:true},
    {name:"Commune",level:5,cleric:true},
    {name:"Commune with Nature",level:5,druid:true,ranger:true},
    {name:"Cone of Cold",level:5,sorcerer:true,wizard:true},
    {name:"Conjure Elemental",level:5,druid:true,wizard:true},
    {name:"Conjure Volley",level:5,ranger:true},
    {name:"Contact Other Plane",level:5,warlock:true,wizard:true},
    {name:"Contagion",level:5,cleric:true,druid:true},
    {name:"Control Winds",level:5,druid:true,sorcerer:true,wizard:true},
    {name:"Creation",level:5,sorcerer:true,wizard:true},
    {name:"Destructive Wave",level:5,paladin:true},
    {name:"Dispel Evil and Good",level:5,cleric:true,paladin:true},
    {name:"Dominate Person",level:5,bard:true,sorcerer:true,wizard:true},
    {name:"Dream",level:5,bard:true,warlock:true,wizard:true},
    {name:"Flame Strike",level:5,cleric:true},
    {name:"Geas",level:5,bard:true,cleric:true,druid:true,paladin:true,wizard:true},
    {name:"Greater Restoration",level:5,bard:true,cleric:true,druid:true},
    {name:"Hallow",level:5,cleric:true},
    {name:"Hold Monster",level:5,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Immolation",level:5,sorcerer:true,wizard:true},
    {name:"Insect Plague",level:5,cleric:true,druid:true,sorcerer:true},
    {name:"Legend Lore",level:5,bard:true,cleric:true,wizard:true},
    {name:"Maelstrom",level:5,druid:true},
    {name:"Mass Cure Wounds",level:5,bard:true,cleric:true,druid:true},
    {name:"Mislead",level:5,bard:true,wizard:true},
    {name:"Modify Memory",level:5,bard:true,wizard:true},
    {name:"Passwall",level:5,wizard:true},
    {name:"Planar Binding",level:5,bard:true,cleric:true,druid:true,wizard:true},
    {name:"Raise Dead",level:5,bard:true,cleric:true,paladin:true},
    {name:"Rary's Telepathic Bond",level:5,wizard:true},
    {name:"Reincarnate",level:5,druid:true},
    {name:"Scrying",level:5,bard:true,cleric:true,druid:true,warlock:true,wizard:true},
    {name:"Seeming",level:5,bard:true,sorcerer:true,wizard:true},
    {name:"Swift Quiver",level:5,ranger:true},
    {name:"Telekinesis",level:5,sorcerer:true,wizard:true},
    {name:"Teleportation Circle",level:5,bard:true,sorcerer:true,wizard:true},
    {name:"Transmute Rock",level:5,druid:true,wizard:true},
    {name:"Tree Stride",level:5,druid:true,ranger:true},
    {name:"Wall of Force",level:5,wizard:true},
    {name:"Wall of Stone",level:5,druid:true,sorcerer:true,wizard:true},
    {name:"Arcane Gate",level:6,sorcerer:true,warlock:true,wizard:true},
    {name:"Blade Barrier",level:6,cleric:true},
    {name:"Bones of the Earth",level:6,druid:true},
    {name:"Chain Lightning",level:6,sorcerer:true,wizard:true},
    {name:"Circle of Death",level:6,sorcerer:true,warlock:true,wizard:true},
    {name:"Conjure Fey",level:6,druid:true,warlock:true},
    {name:"Contingency",level:6,wizard:true},
    {name:"Create Undead",level:6,cleric:true,warlock:true,wizard:true},
    {name:"Disintigrate",level:6,sorcerer:true,wizard:true},
    {name:"Drawmij's Instant Summons",level:6,wizard:true},
    {name:"Eyebite",level:6,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Find the Path",level:6,bard:true,cleric:true,druid:true},
    {name:"Flesh to Stone",level:6,warlock:true,wizard:true},
    {name:"Forbiddance",level:6,cleric:true},
    {name:"Globe of Invulnerability",level:6,sorcerer:true,wizard:true},
    {name:"Guards and Wards",level:6,bard:true,wizard:true},
    {name:"Harm",level:6,cleric:true},
    {name:"Heal",level:6,cleric:true,druid:true},
    {name:"Heroes' Feast",level:6,cleric:true,druid:true},
    {name:"Investiture of Flame",level:6,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Investiture of Ice",level:6,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Investiture of Stone",level:6,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Investiture of Wind",level:6,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Magic Jar",level:6,wizard:true},
    {name:"Mass Suggestion",level:6,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Move Earth",level:6,druid:true,sorcerer:true,wizard:true},
    {name:"Otiluke's Freezing Sphere",level:6,wizard:true},
    {name:"Otto's Irresistable Dance",level:6,bard:true,wizard:true},
    {name:"Planar Ally",level:6,cleric:true},
    {name:"Primordial Ward",level:6,druid:true},
    {name:"Programmed Illusion",level:6,bard:true,wizard:true},
    {name:"Sunbeam",level:6,druid:true,sorcerer:true,wizard:true},
    {name:"Transport via Plants",level:6,druid:true},
    {name:"True Seeing",level:6,bard:true,cleric:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Wall of Ice",level:6,wizard:true},
    {name:"Wall of Thorns",level:6,druid:true},
    {name:"Wind Walk",level:6,druid:true},
    {name:"Word of Recall",level:6,cleric:true},
    {name:"Conjure Celestial",level:7,cleric:true},
    {name:"Delayed Blast Fireball",level:7,sorcerer:true,wizard:true},
    {name:"Divine Word",level:7,cleric:true},
    {name:"Etherealness",level:7,bard:true,cleric:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Finger of Death",level:7,sorcerer:true,warlock:true,wizard:true},
    {name:"Fire Storm",level:7,cleric:true,druid:true,sorcerer:true},
    {name:"Forcecage",level:7,bard:true,warlock:true,wizard:true},
    {name:"Mirage Arcane",level:7,bard:true,druid:true,wizard:true},
    {name:"Mordenkainen's Magnificent Mansion",level:7,bard:true,wizard:true},
    {name:"Mordenkainen's Sword",level:7,bard:true},
    {name:"Plane Shift",level:7,cleric:true,druid:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Prismatic Spray",level:7,sorcerer:true,wizard:true},
    {name:"Project Image",level:7,bard:true,wizard:true},
    {name:"Regenerate",level:7,bard:true,cleric:true,druid:true},
    {name:"Resurrection",level:7,bard:true,cleric:true},
    {name:"Reverse Gravity",level:7,druid:true,sorcerer:true,wizard:true},
    {name:"Sequester",level:7,wizard:true},
    {name:"Simulacrum",level:7,wizard:true},
    {name:"Symbol",level:7,bard:true,cleric:true,wizard:true},
    {name:"Teleport",level:7,bard:true,sorcerer:true,wizard:true},
    {name:"Whirlwind",level:7,druid:true,wizard:true},
    {name:"Abi-Dalzim's Horrid Wilting",level:8,sorcerer:true,wizard:true},
    {name:"Animal Shapes",level:8,druid:true},
    {name:"Antimagic Field",level:8,cleric:true,wizard:true},
    {name:"Antipathy/Sympathy",level:8,druid:true,wizard:true},
    {name:"Clone",level:8,wizard:true},
    {name:"Control Weather",level:8,cleric:true,druid:true,wizard:true},
    {name:"Demiplane",level:8,warlock:true,wizard:true},
    {name:"Dominate Monster",level:8,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Earthquake",level:8,cleric:true,druid:true,sorcerer:true},
    {name:"Feeblemind",level:8,bard:true,druid:true,warlock:true,wizard:true},
    {name:"Glibness",level:8,bard:true,warlock:true},
    {name:"Holy Aura",level:8,cleric:true},
    {name:"Incendiary Cloud",level:8,sorcerer:true,wizard:true},
    {name:"Maze",level:8,wizard:true},
    {name:"Mind Blank",level:8,bard:true,wizard:true},
    {name:"Power Word Stun",level:8,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Sunburst",level:8,druid:true,sorcerer:true,wizard:true},
    {name:"Telepathy",level:8,wizard:true},
    {name:"Tsunami",level:8,druid:true},
    {name:"Astral Projection",level:9,cleric:true,warlock:true,wizard:true},
    {name:"Foresight",level:9,bard:true,druid:true,warlock:true,wizard:true},
    {name:"Gate",level:9,cleric:true,sorcerer:true,wizard:true},
    {name:"Imprisonment",level:9,warlock:true,wizard:true},
    {name:"Mass Heal",level:9,cleric:true},
    {name:"Meteor Swarm",level:9,sorcerer:true,wizard:true},
    {name:"Power Word Heal",level:9,bard:true},
    {name:"Power Word Kill",level:9,bard:true,sorcerer:true,warlock:true,wizard:true},
    {name:"Prismatic Wall",level:9,wizard:true},
    {name:"Shapechange",level:9,druid:true,wizard:true},
    {name:"Storm of Vengeance",level:9,druid:true},
    {name:"Time Stop",level:9,sorcerer:true,wizard:true},
    {name:"True Polymorph",level:9,bard:true,warlock:true,wizard:true},
    {name:"True Resurrection",level:9,cleric:true,druid:true},
    {name:"Weird",level:9,wizard:true},
    {name:"Wish",level:9,sorcerer:true,wizard:true}
];

function spellLevel(lvl, cl) {
    var spellArray = []
    switch (cl) {
        case "Bard":
        for (var sp in spells) {
            if ((spells[sp].level == lvl) && (spells[sp].bard == true)) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Cleric":
        for (var sp in spells) {
            if ((spells[sp].level == lvl) && (spells[sp].cleric == true)) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Druid":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].druid == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Paladin":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].paladin == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Ranger":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].ranger == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Sorcerer":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].sorcerer == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Warlock":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].warlock == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
        case "Wizard":
        for (var sp in spells) {
            if (spells[sp].level == lvl && spells[sp].wizard == true) {
                spellArray.push(spells[sp]);
            }
        }
        break;
    }
    return spellArray;
}